// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityListMembership.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityListMembership::UPFEntityListMembership(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FListMembershipDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityListMembership* UPFEntityListMembership::ListMembership(class APlayerController* PlayerController, const FBPEntityListMembershipRequest& InListMembershipRequest)
{
    UPFEntityListMembership* Proxy = NewObject<UPFEntityListMembership>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InListMembershipRequest;
    
    return Proxy;
}

void UPFEntityListMembership::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->ListMembership(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityListMembership::OnSuccessCallback(const PlayFab::EntityModels::FListMembershipResponse& Result)
{
    FBPEntityListMembershipResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
