// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityUpdateRole.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityUpdateRole::UPFEntityUpdateRole(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FUpdateRoleDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityUpdateRole* UPFEntityUpdateRole::UpdateRole(class APlayerController* PlayerController, const FBPEntityUpdateGroupRoleRequest& InUpdateGroupRoleRequest)
{
    UPFEntityUpdateRole* Proxy = NewObject<UPFEntityUpdateRole>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateGroupRoleRequest;
    
    return Proxy;
}

void UPFEntityUpdateRole::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->UpdateRole(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityUpdateRole::OnSuccessCallback(const PlayFab::EntityModels::FUpdateGroupRoleResponse& Result)
{
    FBPEntityUpdateGroupRoleResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
