// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityDeleteGroup.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityDeleteGroup::UPFEntityDeleteGroup(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FDeleteGroupDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityDeleteGroup* UPFEntityDeleteGroup::DeleteGroup(class APlayerController* PlayerController, const FBPEntityDeleteGroupRequest& InDeleteGroupRequest)
{
    UPFEntityDeleteGroup* Proxy = NewObject<UPFEntityDeleteGroup>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InDeleteGroupRequest;
    
    return Proxy;
}

void UPFEntityDeleteGroup::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->DeleteGroup(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityDeleteGroup::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
