// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityChangeMemberRole.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityChangeMemberRole::UPFEntityChangeMemberRole(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FChangeMemberRoleDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityChangeMemberRole* UPFEntityChangeMemberRole::ChangeMemberRole(class APlayerController* PlayerController, const FBPEntityChangeMemberRoleRequest& InChangeMemberRoleRequest)
{
    UPFEntityChangeMemberRole* Proxy = NewObject<UPFEntityChangeMemberRole>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InChangeMemberRoleRequest;
    
    return Proxy;
}

void UPFEntityChangeMemberRole::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->ChangeMemberRole(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityChangeMemberRole::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
