// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityRemoveGroupInvitation.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityRemoveGroupInvitation::UPFEntityRemoveGroupInvitation(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FRemoveGroupInvitationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityRemoveGroupInvitation* UPFEntityRemoveGroupInvitation::RemoveGroupInvitation(class APlayerController* PlayerController, const FBPEntityRemoveGroupInvitationRequest& InRemoveGroupInvitationRequest)
{
    UPFEntityRemoveGroupInvitation* Proxy = NewObject<UPFEntityRemoveGroupInvitation>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRemoveGroupInvitationRequest;
    
    return Proxy;
}

void UPFEntityRemoveGroupInvitation::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->RemoveGroupInvitation(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityRemoveGroupInvitation::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
