// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityUpdateGroup.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityUpdateGroup::UPFEntityUpdateGroup(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FUpdateGroupDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityUpdateGroup* UPFEntityUpdateGroup::UpdateGroup(class APlayerController* PlayerController, const FBPEntityUpdateGroupRequest& InUpdateGroupRequest)
{
    UPFEntityUpdateGroup* Proxy = NewObject<UPFEntityUpdateGroup>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUpdateGroupRequest;
    
    return Proxy;
}

void UPFEntityUpdateGroup::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->UpdateGroup(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityUpdateGroup::OnSuccessCallback(const PlayFab::EntityModels::FUpdateGroupResponse& Result)
{
    FBPEntityUpdateGroupResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
