// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityInviteToGroup.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityInviteToGroup::UPFEntityInviteToGroup(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FInviteToGroupDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityInviteToGroup* UPFEntityInviteToGroup::InviteToGroup(class APlayerController* PlayerController, const FBPEntityInviteToGroupRequest& InInviteToGroupRequest)
{
    UPFEntityInviteToGroup* Proxy = NewObject<UPFEntityInviteToGroup>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InInviteToGroupRequest;
    
    return Proxy;
}

void UPFEntityInviteToGroup::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->InviteToGroup(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityInviteToGroup::OnSuccessCallback(const PlayFab::EntityModels::FInviteToGroupResponse& Result)
{
    FBPEntityInviteToGroupResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
