// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityListGroupMembers.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityListGroupMembers::UPFEntityListGroupMembers(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FListGroupMembersDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityListGroupMembers* UPFEntityListGroupMembers::ListGroupMembers(class APlayerController* PlayerController, const FBPEntityListGroupMembersRequest& InListGroupMembersRequest)
{
    UPFEntityListGroupMembers* Proxy = NewObject<UPFEntityListGroupMembers>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InListGroupMembersRequest;
    
    return Proxy;
}

void UPFEntityListGroupMembers::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->ListGroupMembers(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityListGroupMembers::OnSuccessCallback(const PlayFab::EntityModels::FListGroupMembersResponse& Result)
{
    FBPEntityListGroupMembersResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
