// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntitySetObjects.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntitySetObjects::UPFEntitySetObjects(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FSetObjectsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntitySetObjects* UPFEntitySetObjects::SetObjects(class APlayerController* PlayerController, const FBPEntitySetObjectsRequest& InSetObjectsRequest)
{
    UPFEntitySetObjects* Proxy = NewObject<UPFEntitySetObjects>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InSetObjectsRequest;
    
    return Proxy;
}

void UPFEntitySetObjects::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->SetObjects(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntitySetObjects::OnSuccessCallback(const PlayFab::EntityModels::FSetObjectsResponse& Result)
{
    FBPEntitySetObjectsResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
