// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityCreateGroup.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityCreateGroup::UPFEntityCreateGroup(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FCreateGroupDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityCreateGroup* UPFEntityCreateGroup::CreateGroup(class APlayerController* PlayerController, const FBPEntityCreateGroupRequest& InCreateGroupRequest)
{
    UPFEntityCreateGroup* Proxy = NewObject<UPFEntityCreateGroup>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InCreateGroupRequest;
    
    return Proxy;
}

void UPFEntityCreateGroup::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->CreateGroup(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityCreateGroup::OnSuccessCallback(const PlayFab::EntityModels::FCreateGroupResponse& Result)
{
    FBPEntityCreateGroupResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
