// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityAcceptGroupApplication.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityAcceptGroupApplication::UPFEntityAcceptGroupApplication(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FAcceptGroupApplicationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityAcceptGroupApplication* UPFEntityAcceptGroupApplication::AcceptGroupApplication(class APlayerController* PlayerController, const FBPEntityAcceptGroupApplicationRequest& InAcceptGroupApplicationRequest)
{
    UPFEntityAcceptGroupApplication* Proxy = NewObject<UPFEntityAcceptGroupApplication>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InAcceptGroupApplicationRequest;
    
    return Proxy;
}

void UPFEntityAcceptGroupApplication::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->AcceptGroupApplication(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityAcceptGroupApplication::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
