// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityGetProfile.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityGetProfile::UPFEntityGetProfile(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FGetProfileDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityGetProfile* UPFEntityGetProfile::GetProfile(class APlayerController* PlayerController, const FBPEntityGetEntityProfileRequest& InGetEntityProfileRequest)
{
    UPFEntityGetProfile* Proxy = NewObject<UPFEntityGetProfile>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetEntityProfileRequest;
    
    return Proxy;
}

void UPFEntityGetProfile::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->GetProfile(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityGetProfile::OnSuccessCallback(const PlayFab::EntityModels::FGetEntityProfileResponse& Result)
{
    FBPEntityGetEntityProfileResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
