// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityFinalizeFileUploads.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityFinalizeFileUploads::UPFEntityFinalizeFileUploads(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FFinalizeFileUploadsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityFinalizeFileUploads* UPFEntityFinalizeFileUploads::FinalizeFileUploads(class APlayerController* PlayerController, const FBPEntityFinalizeFileUploadsRequest& InFinalizeFileUploadsRequest)
{
    UPFEntityFinalizeFileUploads* Proxy = NewObject<UPFEntityFinalizeFileUploads>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InFinalizeFileUploadsRequest;
    
    return Proxy;
}

void UPFEntityFinalizeFileUploads::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->FinalizeFileUploads(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityFinalizeFileUploads::OnSuccessCallback(const PlayFab::EntityModels::FFinalizeFileUploadsResponse& Result)
{
    FBPEntityFinalizeFileUploadsResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
