// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityGetProfiles.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityGetProfiles::UPFEntityGetProfiles(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FGetProfilesDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityGetProfiles* UPFEntityGetProfiles::GetProfiles(class APlayerController* PlayerController, const FBPEntityGetEntityProfilesRequest& InGetEntityProfilesRequest)
{
    UPFEntityGetProfiles* Proxy = NewObject<UPFEntityGetProfiles>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetEntityProfilesRequest;
    
    return Proxy;
}

void UPFEntityGetProfiles::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->GetProfiles(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityGetProfiles::OnSuccessCallback(const PlayFab::EntityModels::FGetEntityProfilesResponse& Result)
{
    FBPEntityGetEntityProfilesResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
