// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityGetEntityToken.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityGetEntityToken::UPFEntityGetEntityToken(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FGetEntityTokenDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityGetEntityToken* UPFEntityGetEntityToken::GetEntityToken(class APlayerController* PlayerController, const FBPEntityGetEntityTokenRequest& InGetEntityTokenRequest)
{
    UPFEntityGetEntityToken* Proxy = NewObject<UPFEntityGetEntityToken>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InGetEntityTokenRequest;
    
    return Proxy;
}

void UPFEntityGetEntityToken::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->GetEntityToken(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityGetEntityToken::OnSuccessCallback(const PlayFab::EntityModels::FGetEntityTokenResponse& Result)
{
    FBPEntityGetEntityTokenResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
