// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityIsMember.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityIsMember::UPFEntityIsMember(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FIsMemberDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityIsMember* UPFEntityIsMember::IsMember(class APlayerController* PlayerController, const FBPEntityIsMemberRequest& InIsMemberRequest)
{
    UPFEntityIsMember* Proxy = NewObject<UPFEntityIsMember>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InIsMemberRequest;
    
    return Proxy;
}

void UPFEntityIsMember::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->IsMember(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityIsMember::OnSuccessCallback(const PlayFab::EntityModels::FIsMemberResponse& Result)
{
    FBPEntityIsMemberResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
