// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityRemoveMembers.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityRemoveMembers::UPFEntityRemoveMembers(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FRemoveMembersDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityRemoveMembers* UPFEntityRemoveMembers::RemoveMembers(class APlayerController* PlayerController, const FBPEntityRemoveMembersRequest& InRemoveMembersRequest)
{
    UPFEntityRemoveMembers* Proxy = NewObject<UPFEntityRemoveMembers>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRemoveMembersRequest;
    
    return Proxy;
}

void UPFEntityRemoveMembers::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->RemoveMembers(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityRemoveMembers::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
