// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityCreateRole.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityCreateRole::UPFEntityCreateRole(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FCreateRoleDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityCreateRole* UPFEntityCreateRole::CreateRole(class APlayerController* PlayerController, const FBPEntityCreateGroupRoleRequest& InCreateGroupRoleRequest)
{
    UPFEntityCreateRole* Proxy = NewObject<UPFEntityCreateRole>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InCreateGroupRoleRequest;
    
    return Proxy;
}

void UPFEntityCreateRole::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->CreateRole(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityCreateRole::OnSuccessCallback(const PlayFab::EntityModels::FCreateGroupRoleResponse& Result)
{
    FBPEntityCreateGroupRoleResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
