// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityRemoveGroupApplication.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityRemoveGroupApplication::UPFEntityRemoveGroupApplication(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FRemoveGroupApplicationDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityRemoveGroupApplication* UPFEntityRemoveGroupApplication::RemoveGroupApplication(class APlayerController* PlayerController, const FBPEntityRemoveGroupApplicationRequest& InRemoveGroupApplicationRequest)
{
    UPFEntityRemoveGroupApplication* Proxy = NewObject<UPFEntityRemoveGroupApplication>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRemoveGroupApplicationRequest;
    
    return Proxy;
}

void UPFEntityRemoveGroupApplication::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->RemoveGroupApplication(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityRemoveGroupApplication::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
