// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityUnblockEntity.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityUnblockEntity::UPFEntityUnblockEntity(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FUnblockEntityDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityUnblockEntity* UPFEntityUnblockEntity::UnblockEntity(class APlayerController* PlayerController, const FBPEntityUnblockEntityRequest& InUnblockEntityRequest)
{
    UPFEntityUnblockEntity* Proxy = NewObject<UPFEntityUnblockEntity>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InUnblockEntityRequest;
    
    return Proxy;
}

void UPFEntityUnblockEntity::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->UnblockEntity(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityUnblockEntity::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
