// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntitySetGlobalPolicy.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntitySetGlobalPolicy::UPFEntitySetGlobalPolicy(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FSetGlobalPolicyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntitySetGlobalPolicy* UPFEntitySetGlobalPolicy::SetGlobalPolicy(class APlayerController* PlayerController, const FBPEntitySetGlobalPolicyRequest& InSetGlobalPolicyRequest)
{
    UPFEntitySetGlobalPolicy* Proxy = NewObject<UPFEntitySetGlobalPolicy>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InSetGlobalPolicyRequest;
    
    return Proxy;
}

void UPFEntitySetGlobalPolicy::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->SetGlobalPolicy(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntitySetGlobalPolicy::OnSuccessCallback(const PlayFab::EntityModels::FSetGlobalPolicyResponse& Result)
{
    OnSuccess.Broadcast();
}
