// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityBlockEntity.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityBlockEntity::UPFEntityBlockEntity(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FBlockEntityDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityBlockEntity* UPFEntityBlockEntity::BlockEntity(class APlayerController* PlayerController, const FBPEntityBlockEntityRequest& InBlockEntityRequest)
{
    UPFEntityBlockEntity* Proxy = NewObject<UPFEntityBlockEntity>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InBlockEntityRequest;
    
    return Proxy;
}

void UPFEntityBlockEntity::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->BlockEntity(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityBlockEntity::OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result)
{
    OnSuccess.Broadcast();
}
