// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityGetGlobalPolicy.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityGetGlobalPolicy::UPFEntityGetGlobalPolicy(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FGetGlobalPolicyDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityGetGlobalPolicy* UPFEntityGetGlobalPolicy::GetGlobalPolicy(class APlayerController* PlayerController)
{
    UPFEntityGetGlobalPolicy* Proxy = NewObject<UPFEntityGetGlobalPolicy>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    
    return Proxy;
}

void UPFEntityGetGlobalPolicy::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->GetGlobalPolicy(SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityGetGlobalPolicy::OnSuccessCallback(const PlayFab::EntityModels::FGetGlobalPolicyResponse& Result)
{
    FBPEntityGetGlobalPolicyResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
