// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFEntityListGroupBlocks.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFEntityListGroupBlocks::UPFEntityListGroupBlocks(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabEntityAPI::FListGroupBlocksDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFEntityListGroupBlocks* UPFEntityListGroupBlocks::ListGroupBlocks(class APlayerController* PlayerController, const FBPEntityListGroupBlocksRequest& InListGroupBlocksRequest)
{
    UPFEntityListGroupBlocks* Proxy = NewObject<UPFEntityListGroupBlocks>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InListGroupBlocksRequest;
    
    return Proxy;
}

void UPFEntityListGroupBlocks::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabEntityPtr EntityAPI = IPlayFabModuleInterface::Get().GetEntityAPI();

    bool CallResult = false;

    if (EntityAPI.IsValid())
    {
        CallResult = EntityAPI->ListGroupBlocks(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFEntityListGroupBlocks::OnSuccessCallback(const PlayFab::EntityModels::FListGroupBlocksResponse& Result)
{
    FBPEntityListGroupBlocksResponse BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
