// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "PlayFabEntityBPDataModels.generated.h"

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityAbortFileUploadsRequest"))
struct FBPEntityAbortFileUploadsRequest
{
    GENERATED_BODY()
public:
    FBPEntityAbortFileUploadsRequest() {};
    FBPEntityAbortFileUploadsRequest(PlayFab::EntityModels::FAbortFileUploadsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FAbortFileUploadsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityAbortFileUploadsResponse"))
struct FBPEntityAbortFileUploadsResponse
{
    GENERATED_BODY()
public:
    FBPEntityAbortFileUploadsResponse() {};
    FBPEntityAbortFileUploadsResponse(PlayFab::EntityModels::FAbortFileUploadsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FAbortFileUploadsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityAcceptGroupApplicationRequest"))
struct FBPEntityAcceptGroupApplicationRequest
{
    GENERATED_BODY()
public:
    FBPEntityAcceptGroupApplicationRequest() {};
    FBPEntityAcceptGroupApplicationRequest(PlayFab::EntityModels::FAcceptGroupApplicationRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FAcceptGroupApplicationRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityAcceptGroupInvitationRequest"))
struct FBPEntityAcceptGroupInvitationRequest
{
    GENERATED_BODY()
public:
    FBPEntityAcceptGroupInvitationRequest() {};
    FBPEntityAcceptGroupInvitationRequest(PlayFab::EntityModels::FAcceptGroupInvitationRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FAcceptGroupInvitationRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityAddMembersRequest"))
struct FBPEntityAddMembersRequest
{
    GENERATED_BODY()
public:
    FBPEntityAddMembersRequest() {};
    FBPEntityAddMembersRequest(PlayFab::EntityModels::FAddMembersRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FAddMembersRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityApplyToGroupRequest"))
struct FBPEntityApplyToGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityApplyToGroupRequest() {};
    FBPEntityApplyToGroupRequest(PlayFab::EntityModels::FApplyToGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FApplyToGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityApplyToGroupResponse"))
struct FBPEntityApplyToGroupResponse
{
    GENERATED_BODY()
public:
    FBPEntityApplyToGroupResponse() {};
    FBPEntityApplyToGroupResponse(PlayFab::EntityModels::FApplyToGroupResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FApplyToGroupResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityBlockEntityRequest"))
struct FBPEntityBlockEntityRequest
{
    GENERATED_BODY()
public:
    FBPEntityBlockEntityRequest() {};
    FBPEntityBlockEntityRequest(PlayFab::EntityModels::FBlockEntityRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FBlockEntityRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityChangeMemberRoleRequest"))
struct FBPEntityChangeMemberRoleRequest
{
    GENERATED_BODY()
public:
    FBPEntityChangeMemberRoleRequest() {};
    FBPEntityChangeMemberRoleRequest(PlayFab::EntityModels::FChangeMemberRoleRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FChangeMemberRoleRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityCreateGroupRequest"))
struct FBPEntityCreateGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityCreateGroupRequest() {};
    FBPEntityCreateGroupRequest(PlayFab::EntityModels::FCreateGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FCreateGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityCreateGroupResponse"))
struct FBPEntityCreateGroupResponse
{
    GENERATED_BODY()
public:
    FBPEntityCreateGroupResponse() {};
    FBPEntityCreateGroupResponse(PlayFab::EntityModels::FCreateGroupResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FCreateGroupResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityCreateGroupRoleRequest"))
struct FBPEntityCreateGroupRoleRequest
{
    GENERATED_BODY()
public:
    FBPEntityCreateGroupRoleRequest() {};
    FBPEntityCreateGroupRoleRequest(PlayFab::EntityModels::FCreateGroupRoleRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FCreateGroupRoleRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityCreateGroupRoleResponse"))
struct FBPEntityCreateGroupRoleResponse
{
    GENERATED_BODY()
public:
    FBPEntityCreateGroupRoleResponse() {};
    FBPEntityCreateGroupRoleResponse(PlayFab::EntityModels::FCreateGroupRoleResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FCreateGroupRoleResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityDeleteFilesRequest"))
struct FBPEntityDeleteFilesRequest
{
    GENERATED_BODY()
public:
    FBPEntityDeleteFilesRequest() {};
    FBPEntityDeleteFilesRequest(PlayFab::EntityModels::FDeleteFilesRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FDeleteFilesRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityDeleteFilesResponse"))
struct FBPEntityDeleteFilesResponse
{
    GENERATED_BODY()
public:
    FBPEntityDeleteFilesResponse() {};
    FBPEntityDeleteFilesResponse(PlayFab::EntityModels::FDeleteFilesResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FDeleteFilesResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityDeleteGroupRequest"))
struct FBPEntityDeleteGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityDeleteGroupRequest() {};
    FBPEntityDeleteGroupRequest(PlayFab::EntityModels::FDeleteGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FDeleteGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityDeleteRoleRequest"))
struct FBPEntityDeleteRoleRequest
{
    GENERATED_BODY()
public:
    FBPEntityDeleteRoleRequest() {};
    FBPEntityDeleteRoleRequest(PlayFab::EntityModels::FDeleteRoleRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FDeleteRoleRequest Data;
};

UENUM(BlueprintType)
enum class EBPEntityEffectType : uint8
{
    EffectType_Allow UMETA(DisplayName = "Allow"),
    EffectType_Deny UMETA(DisplayName = "Deny")
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEmptyResult"))
struct FBPEntityEmptyResult
{
    GENERATED_BODY()
public:
    FBPEntityEmptyResult() {};
    FBPEntityEmptyResult(PlayFab::EntityModels::FEmptyResult InData) : Data(InData) {};
    PlayFab::EntityModels::FEmptyResult Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityDataObject", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityDataObject"))
struct FBPEntityEntityDataObject
{
    GENERATED_BODY()
public:
    FBPEntityEntityDataObject() {};
    FBPEntityEntityDataObject(PlayFab::EntityModels::FEntityDataObject InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityDataObject Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityKey", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityKey"))
struct FBPEntityEntityKey
{
    GENERATED_BODY()
public:
    FBPEntityEntityKey() {};
    FBPEntityEntityKey(PlayFab::EntityModels::FEntityKey InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityKey Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityMemberRole", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityMemberRole"))
struct FBPEntityEntityMemberRole
{
    GENERATED_BODY()
public:
    FBPEntityEntityMemberRole() {};
    FBPEntityEntityMemberRole(PlayFab::EntityModels::FEntityMemberRole InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityMemberRole Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityPermissionStatement", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityPermissionStatement"))
struct FBPEntityEntityPermissionStatement
{
    GENERATED_BODY()
public:
    FBPEntityEntityPermissionStatement() {};
    FBPEntityEntityPermissionStatement(PlayFab::EntityModels::FEntityPermissionStatement InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityPermissionStatement Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityProfileBody", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityProfileBody"))
struct FBPEntityEntityProfileBody
{
    GENERATED_BODY()
public:
    FBPEntityEntityProfileBody() {};
    FBPEntityEntityProfileBody(PlayFab::EntityModels::FEntityProfileBody InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityProfileBody Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityProfileFileMetadata", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityProfileFileMetadata"))
struct FBPEntityEntityProfileFileMetadata
{
    GENERATED_BODY()
public:
    FBPEntityEntityProfileFileMetadata() {};
    FBPEntityEntityProfileFileMetadata(PlayFab::EntityModels::FEntityProfileFileMetadata InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityProfileFileMetadata Data;
};

UENUM(BlueprintType)
enum class EBPEntityEntityTypes : uint8
{
    EntityTypes_title UMETA(DisplayName = "title"),
    EntityTypes_master_player_account UMETA(DisplayName = "master_player_account"),
    EntityTypes_title_player_account UMETA(DisplayName = "title_player_account"),
    EntityTypes_character UMETA(DisplayName = "character"),
    EntityTypes_group UMETA(DisplayName = "group"),
    EntityTypes_service UMETA(DisplayName = "service")
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityEntityWithLineage", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityEntityWithLineage"))
struct FBPEntityEntityWithLineage
{
    GENERATED_BODY()
public:
    FBPEntityEntityWithLineage() {};
    FBPEntityEntityWithLineage(PlayFab::EntityModels::FEntityWithLineage InData) : Data(InData) {};
    PlayFab::EntityModels::FEntityWithLineage Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityFinalizeFileUploadsRequest"))
struct FBPEntityFinalizeFileUploadsRequest
{
    GENERATED_BODY()
public:
    FBPEntityFinalizeFileUploadsRequest() {};
    FBPEntityFinalizeFileUploadsRequest(PlayFab::EntityModels::FFinalizeFileUploadsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FFinalizeFileUploadsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityFinalizeFileUploadsResponse"))
struct FBPEntityFinalizeFileUploadsResponse
{
    GENERATED_BODY()
public:
    FBPEntityFinalizeFileUploadsResponse() {};
    FBPEntityFinalizeFileUploadsResponse(PlayFab::EntityModels::FFinalizeFileUploadsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FFinalizeFileUploadsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetEntityProfileRequest"))
struct FBPEntityGetEntityProfileRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityProfileRequest() {};
    FBPEntityGetEntityProfileRequest(PlayFab::EntityModels::FGetEntityProfileRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityProfileRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetEntityProfileResponse"))
struct FBPEntityGetEntityProfileResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityProfileResponse() {};
    FBPEntityGetEntityProfileResponse(PlayFab::EntityModels::FGetEntityProfileResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityProfileResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetEntityProfilesRequest"))
struct FBPEntityGetEntityProfilesRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityProfilesRequest() {};
    FBPEntityGetEntityProfilesRequest(PlayFab::EntityModels::FGetEntityProfilesRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityProfilesRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetEntityProfilesResponse"))
struct FBPEntityGetEntityProfilesResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityProfilesResponse() {};
    FBPEntityGetEntityProfilesResponse(PlayFab::EntityModels::FGetEntityProfilesResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityProfilesResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetEntityTokenRequest"))
struct FBPEntityGetEntityTokenRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityTokenRequest() {};
    FBPEntityGetEntityTokenRequest(PlayFab::EntityModels::FGetEntityTokenRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityTokenRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetEntityTokenResponse"))
struct FBPEntityGetEntityTokenResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetEntityTokenResponse() {};
    FBPEntityGetEntityTokenResponse(PlayFab::EntityModels::FGetEntityTokenResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetEntityTokenResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetFileMetadata", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetFileMetadata"))
struct FBPEntityGetFileMetadata
{
    GENERATED_BODY()
public:
    FBPEntityGetFileMetadata() {};
    FBPEntityGetFileMetadata(PlayFab::EntityModels::FGetFileMetadata InData) : Data(InData) {};
    PlayFab::EntityModels::FGetFileMetadata Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetFilesRequest"))
struct FBPEntityGetFilesRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetFilesRequest() {};
    FBPEntityGetFilesRequest(PlayFab::EntityModels::FGetFilesRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetFilesRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetFilesResponse"))
struct FBPEntityGetFilesResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetFilesResponse() {};
    FBPEntityGetFilesResponse(PlayFab::EntityModels::FGetFilesResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetFilesResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetGlobalPolicyRequest"))
struct FBPEntityGetGlobalPolicyRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetGlobalPolicyRequest() {};
    FBPEntityGetGlobalPolicyRequest(PlayFab::EntityModels::FGetGlobalPolicyRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetGlobalPolicyRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetGlobalPolicyResponse"))
struct FBPEntityGetGlobalPolicyResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetGlobalPolicyResponse() {};
    FBPEntityGetGlobalPolicyResponse(PlayFab::EntityModels::FGetGlobalPolicyResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetGlobalPolicyResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetGroupRequest"))
struct FBPEntityGetGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetGroupRequest() {};
    FBPEntityGetGroupRequest(PlayFab::EntityModels::FGetGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetGroupResponse"))
struct FBPEntityGetGroupResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetGroupResponse() {};
    FBPEntityGetGroupResponse(PlayFab::EntityModels::FGetGroupResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetGroupResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGetObjectsRequest"))
struct FBPEntityGetObjectsRequest
{
    GENERATED_BODY()
public:
    FBPEntityGetObjectsRequest() {};
    FBPEntityGetObjectsRequest(PlayFab::EntityModels::FGetObjectsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FGetObjectsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGetObjectsResponse"))
struct FBPEntityGetObjectsResponse
{
    GENERATED_BODY()
public:
    FBPEntityGetObjectsResponse() {};
    FBPEntityGetObjectsResponse(PlayFab::EntityModels::FGetObjectsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FGetObjectsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGroupApplication", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGroupApplication"))
struct FBPEntityGroupApplication
{
    GENERATED_BODY()
public:
    FBPEntityGroupApplication() {};
    FBPEntityGroupApplication(PlayFab::EntityModels::FGroupApplication InData) : Data(InData) {};
    PlayFab::EntityModels::FGroupApplication Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGroupBlock", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGroupBlock"))
struct FBPEntityGroupBlock
{
    GENERATED_BODY()
public:
    FBPEntityGroupBlock() {};
    FBPEntityGroupBlock(PlayFab::EntityModels::FGroupBlock InData) : Data(InData) {};
    PlayFab::EntityModels::FGroupBlock Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGroupInvitation", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGroupInvitation"))
struct FBPEntityGroupInvitation
{
    GENERATED_BODY()
public:
    FBPEntityGroupInvitation() {};
    FBPEntityGroupInvitation(PlayFab::EntityModels::FGroupInvitation InData) : Data(InData) {};
    PlayFab::EntityModels::FGroupInvitation Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGroupRole", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGroupRole"))
struct FBPEntityGroupRole
{
    GENERATED_BODY()
public:
    FBPEntityGroupRole() {};
    FBPEntityGroupRole(PlayFab::EntityModels::FGroupRole InData) : Data(InData) {};
    PlayFab::EntityModels::FGroupRole Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityGroupWithRoles", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityGroupWithRoles"))
struct FBPEntityGroupWithRoles
{
    GENERATED_BODY()
public:
    FBPEntityGroupWithRoles() {};
    FBPEntityGroupWithRoles(PlayFab::EntityModels::FGroupWithRoles InData) : Data(InData) {};
    PlayFab::EntityModels::FGroupWithRoles Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityInitiateFileUploadMetadata", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityInitiateFileUploadMetadata"))
struct FBPEntityInitiateFileUploadMetadata
{
    GENERATED_BODY()
public:
    FBPEntityInitiateFileUploadMetadata() {};
    FBPEntityInitiateFileUploadMetadata(PlayFab::EntityModels::FInitiateFileUploadMetadata InData) : Data(InData) {};
    PlayFab::EntityModels::FInitiateFileUploadMetadata Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityInitiateFileUploadsRequest"))
struct FBPEntityInitiateFileUploadsRequest
{
    GENERATED_BODY()
public:
    FBPEntityInitiateFileUploadsRequest() {};
    FBPEntityInitiateFileUploadsRequest(PlayFab::EntityModels::FInitiateFileUploadsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FInitiateFileUploadsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityInitiateFileUploadsResponse"))
struct FBPEntityInitiateFileUploadsResponse
{
    GENERATED_BODY()
public:
    FBPEntityInitiateFileUploadsResponse() {};
    FBPEntityInitiateFileUploadsResponse(PlayFab::EntityModels::FInitiateFileUploadsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FInitiateFileUploadsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityInviteToGroupRequest"))
struct FBPEntityInviteToGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityInviteToGroupRequest() {};
    FBPEntityInviteToGroupRequest(PlayFab::EntityModels::FInviteToGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FInviteToGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityInviteToGroupResponse"))
struct FBPEntityInviteToGroupResponse
{
    GENERATED_BODY()
public:
    FBPEntityInviteToGroupResponse() {};
    FBPEntityInviteToGroupResponse(PlayFab::EntityModels::FInviteToGroupResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FInviteToGroupResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityIsMemberRequest"))
struct FBPEntityIsMemberRequest
{
    GENERATED_BODY()
public:
    FBPEntityIsMemberRequest() {};
    FBPEntityIsMemberRequest(PlayFab::EntityModels::FIsMemberRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FIsMemberRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityIsMemberResponse"))
struct FBPEntityIsMemberResponse
{
    GENERATED_BODY()
public:
    FBPEntityIsMemberResponse() {};
    FBPEntityIsMemberResponse(PlayFab::EntityModels::FIsMemberResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FIsMemberResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListGroupApplicationsRequest"))
struct FBPEntityListGroupApplicationsRequest
{
    GENERATED_BODY()
public:
    FBPEntityListGroupApplicationsRequest() {};
    FBPEntityListGroupApplicationsRequest(PlayFab::EntityModels::FListGroupApplicationsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupApplicationsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListGroupApplicationsResponse"))
struct FBPEntityListGroupApplicationsResponse
{
    GENERATED_BODY()
public:
    FBPEntityListGroupApplicationsResponse() {};
    FBPEntityListGroupApplicationsResponse(PlayFab::EntityModels::FListGroupApplicationsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupApplicationsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListGroupBlocksRequest"))
struct FBPEntityListGroupBlocksRequest
{
    GENERATED_BODY()
public:
    FBPEntityListGroupBlocksRequest() {};
    FBPEntityListGroupBlocksRequest(PlayFab::EntityModels::FListGroupBlocksRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupBlocksRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListGroupBlocksResponse"))
struct FBPEntityListGroupBlocksResponse
{
    GENERATED_BODY()
public:
    FBPEntityListGroupBlocksResponse() {};
    FBPEntityListGroupBlocksResponse(PlayFab::EntityModels::FListGroupBlocksResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupBlocksResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListGroupInvitationsRequest"))
struct FBPEntityListGroupInvitationsRequest
{
    GENERATED_BODY()
public:
    FBPEntityListGroupInvitationsRequest() {};
    FBPEntityListGroupInvitationsRequest(PlayFab::EntityModels::FListGroupInvitationsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupInvitationsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListGroupInvitationsResponse"))
struct FBPEntityListGroupInvitationsResponse
{
    GENERATED_BODY()
public:
    FBPEntityListGroupInvitationsResponse() {};
    FBPEntityListGroupInvitationsResponse(PlayFab::EntityModels::FListGroupInvitationsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupInvitationsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListGroupMembersRequest"))
struct FBPEntityListGroupMembersRequest
{
    GENERATED_BODY()
public:
    FBPEntityListGroupMembersRequest() {};
    FBPEntityListGroupMembersRequest(PlayFab::EntityModels::FListGroupMembersRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupMembersRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListGroupMembersResponse"))
struct FBPEntityListGroupMembersResponse
{
    GENERATED_BODY()
public:
    FBPEntityListGroupMembersResponse() {};
    FBPEntityListGroupMembersResponse(PlayFab::EntityModels::FListGroupMembersResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListGroupMembersResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListMembershipOpportunitiesRequest"))
struct FBPEntityListMembershipOpportunitiesRequest
{
    GENERATED_BODY()
public:
    FBPEntityListMembershipOpportunitiesRequest() {};
    FBPEntityListMembershipOpportunitiesRequest(PlayFab::EntityModels::FListMembershipOpportunitiesRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListMembershipOpportunitiesRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListMembershipOpportunitiesResponse"))
struct FBPEntityListMembershipOpportunitiesResponse
{
    GENERATED_BODY()
public:
    FBPEntityListMembershipOpportunitiesResponse() {};
    FBPEntityListMembershipOpportunitiesResponse(PlayFab::EntityModels::FListMembershipOpportunitiesResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListMembershipOpportunitiesResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityListMembershipRequest"))
struct FBPEntityListMembershipRequest
{
    GENERATED_BODY()
public:
    FBPEntityListMembershipRequest() {};
    FBPEntityListMembershipRequest(PlayFab::EntityModels::FListMembershipRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FListMembershipRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityListMembershipResponse"))
struct FBPEntityListMembershipResponse
{
    GENERATED_BODY()
public:
    FBPEntityListMembershipResponse() {};
    FBPEntityListMembershipResponse(PlayFab::EntityModels::FListMembershipResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FListMembershipResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityObjectResult"))
struct FBPEntityObjectResult
{
    GENERATED_BODY()
public:
    FBPEntityObjectResult() {};
    FBPEntityObjectResult(PlayFab::EntityModels::FObjectResult InData) : Data(InData) {};
    PlayFab::EntityModels::FObjectResult Data;
};

UENUM(BlueprintType)
enum class EBPEntityOperationTypes : uint8
{
    OperationTypes_Created UMETA(DisplayName = "Created"),
    OperationTypes_Updated UMETA(DisplayName = "Updated"),
    OperationTypes_Deleted UMETA(DisplayName = "Deleted"),
    OperationTypes_None UMETA(DisplayName = "None")
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityRemoveGroupApplicationRequest"))
struct FBPEntityRemoveGroupApplicationRequest
{
    GENERATED_BODY()
public:
    FBPEntityRemoveGroupApplicationRequest() {};
    FBPEntityRemoveGroupApplicationRequest(PlayFab::EntityModels::FRemoveGroupApplicationRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FRemoveGroupApplicationRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityRemoveGroupInvitationRequest"))
struct FBPEntityRemoveGroupInvitationRequest
{
    GENERATED_BODY()
public:
    FBPEntityRemoveGroupInvitationRequest() {};
    FBPEntityRemoveGroupInvitationRequest(PlayFab::EntityModels::FRemoveGroupInvitationRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FRemoveGroupInvitationRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityRemoveMembersRequest"))
struct FBPEntityRemoveMembersRequest
{
    GENERATED_BODY()
public:
    FBPEntityRemoveMembersRequest() {};
    FBPEntityRemoveMembersRequest(PlayFab::EntityModels::FRemoveMembersRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FRemoveMembersRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntitySetEntityProfilePolicyRequest"))
struct FBPEntitySetEntityProfilePolicyRequest
{
    GENERATED_BODY()
public:
    FBPEntitySetEntityProfilePolicyRequest() {};
    FBPEntitySetEntityProfilePolicyRequest(PlayFab::EntityModels::FSetEntityProfilePolicyRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FSetEntityProfilePolicyRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntitySetEntityProfilePolicyResponse"))
struct FBPEntitySetEntityProfilePolicyResponse
{
    GENERATED_BODY()
public:
    FBPEntitySetEntityProfilePolicyResponse() {};
    FBPEntitySetEntityProfilePolicyResponse(PlayFab::EntityModels::FSetEntityProfilePolicyResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FSetEntityProfilePolicyResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntitySetGlobalPolicyRequest"))
struct FBPEntitySetGlobalPolicyRequest
{
    GENERATED_BODY()
public:
    FBPEntitySetGlobalPolicyRequest() {};
    FBPEntitySetGlobalPolicyRequest(PlayFab::EntityModels::FSetGlobalPolicyRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FSetGlobalPolicyRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntitySetGlobalPolicyResponse"))
struct FBPEntitySetGlobalPolicyResponse
{
    GENERATED_BODY()
public:
    FBPEntitySetGlobalPolicyResponse() {};
    FBPEntitySetGlobalPolicyResponse(PlayFab::EntityModels::FSetGlobalPolicyResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FSetGlobalPolicyResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntitySetObject", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntitySetObject"))
struct FBPEntitySetObject
{
    GENERATED_BODY()
public:
    FBPEntitySetObject() {};
    FBPEntitySetObject(PlayFab::EntityModels::FSetObject InData) : Data(InData) {};
    PlayFab::EntityModels::FSetObject Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntitySetObjectInfo", HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntitySetObjectInfo"))
struct FBPEntitySetObjectInfo
{
    GENERATED_BODY()
public:
    FBPEntitySetObjectInfo() {};
    FBPEntitySetObjectInfo(PlayFab::EntityModels::FSetObjectInfo InData) : Data(InData) {};
    PlayFab::EntityModels::FSetObjectInfo Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntitySetObjectsRequest"))
struct FBPEntitySetObjectsRequest
{
    GENERATED_BODY()
public:
    FBPEntitySetObjectsRequest() {};
    FBPEntitySetObjectsRequest(PlayFab::EntityModels::FSetObjectsRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FSetObjectsRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntitySetObjectsResponse"))
struct FBPEntitySetObjectsResponse
{
    GENERATED_BODY()
public:
    FBPEntitySetObjectsResponse() {};
    FBPEntitySetObjectsResponse(PlayFab::EntityModels::FSetObjectsResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FSetObjectsResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityUnblockEntityRequest"))
struct FBPEntityUnblockEntityRequest
{
    GENERATED_BODY()
public:
    FBPEntityUnblockEntityRequest() {};
    FBPEntityUnblockEntityRequest(PlayFab::EntityModels::FUnblockEntityRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FUnblockEntityRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityUpdateGroupRequest"))
struct FBPEntityUpdateGroupRequest
{
    GENERATED_BODY()
public:
    FBPEntityUpdateGroupRequest() {};
    FBPEntityUpdateGroupRequest(PlayFab::EntityModels::FUpdateGroupRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FUpdateGroupRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityUpdateGroupResponse"))
struct FBPEntityUpdateGroupResponse
{
    GENERATED_BODY()
public:
    FBPEntityUpdateGroupResponse() {};
    FBPEntityUpdateGroupResponse(PlayFab::EntityModels::FUpdateGroupResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FUpdateGroupResponse Data;
};

USTRUCT(BlueprintType, meta = (HasNativeMake = "PlayFabProxy.PFEntityProxyLibrary.MakeBPEntityUpdateGroupRoleRequest"))
struct FBPEntityUpdateGroupRoleRequest
{
    GENERATED_BODY()
public:
    FBPEntityUpdateGroupRoleRequest() {};
    FBPEntityUpdateGroupRoleRequest(PlayFab::EntityModels::FUpdateGroupRoleRequest InData) : Data(InData) {};
    PlayFab::EntityModels::FUpdateGroupRoleRequest Data;
};

USTRUCT(BlueprintType, meta = (HasNativeBreak = "PlayFabProxy.PFEntityProxyLibrary.BreakBPEntityUpdateGroupRoleResponse"))
struct FBPEntityUpdateGroupRoleResponse
{
    GENERATED_BODY()
public:
    FBPEntityUpdateGroupRoleResponse() {};
    FBPEntityUpdateGroupRoleResponse(PlayFab::EntityModels::FUpdateGroupRoleResponse InData) : Data(InData) {};
    PlayFab::EntityModels::FUpdateGroupRoleResponse Data;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityAbortFileUploadsResponseDelegate, const FBPEntityAbortFileUploadsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityApplyToGroupResponseDelegate, const FBPEntityApplyToGroupResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityCreateGroupResponseDelegate, const FBPEntityCreateGroupResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityCreateGroupRoleResponseDelegate, const FBPEntityCreateGroupRoleResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityDeleteFilesResponseDelegate, const FBPEntityDeleteFilesResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityEmptyResultDelegate, const FBPEntityEmptyResult&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityFinalizeFileUploadsResponseDelegate, const FBPEntityFinalizeFileUploadsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetEntityProfileResponseDelegate, const FBPEntityGetEntityProfileResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetEntityProfilesResponseDelegate, const FBPEntityGetEntityProfilesResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetEntityTokenResponseDelegate, const FBPEntityGetEntityTokenResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetFilesResponseDelegate, const FBPEntityGetFilesResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetGlobalPolicyResponseDelegate, const FBPEntityGetGlobalPolicyResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetGroupResponseDelegate, const FBPEntityGetGroupResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityGetObjectsResponseDelegate, const FBPEntityGetObjectsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityInitiateFileUploadsResponseDelegate, const FBPEntityInitiateFileUploadsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityInviteToGroupResponseDelegate, const FBPEntityInviteToGroupResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityIsMemberResponseDelegate, const FBPEntityIsMemberResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListGroupApplicationsResponseDelegate, const FBPEntityListGroupApplicationsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListGroupBlocksResponseDelegate, const FBPEntityListGroupBlocksResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListGroupInvitationsResponseDelegate, const FBPEntityListGroupInvitationsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListGroupMembersResponseDelegate, const FBPEntityListGroupMembersResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListMembershipOpportunitiesResponseDelegate, const FBPEntityListMembershipOpportunitiesResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityListMembershipResponseDelegate, const FBPEntityListMembershipResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityObjectResultDelegate, const FBPEntityObjectResult&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntitySetEntityProfilePolicyResponseDelegate, const FBPEntitySetEntityProfilePolicyResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntitySetGlobalPolicyResponseDelegate, const FBPEntitySetGlobalPolicyResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntitySetObjectsResponseDelegate, const FBPEntitySetObjectsResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityUpdateGroupResponseDelegate, const FBPEntityUpdateGroupResponse&, Result);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FBPEntityUpdateGroupRoleResponseDelegate, const FBPEntityUpdateGroupRoleResponse&, Result);

