// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabServerAPI.h"
#include "Core/PlayFabServerDataModels.h"
#include "Proxy/PlayFabServerBPDataModels.h"
#include "PFServerRevokeInventoryItems.generated.h"

UCLASS(MinimalAPI)
class UPFServerRevokeInventoryItems : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPServerRevokeInventoryItemsResultDelegate OnSuccess;

    // Revokes access for up to 25 items across multiple users and characters.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Server|Player Item Management")
        static UPFServerRevokeInventoryItems* RevokeInventoryItems(class APlayerController* PlayerController, const FBPServerRevokeInventoryItemsRequest& InRevokeInventoryItemsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPServerRevokeInventoryItemsRequest Request;
    PlayFab::UPlayFabServerAPI::FRevokeInventoryItemsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::ServerModels::FRevokeInventoryItemsResult& Result);
};
