// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityGetGroup.generated.h"

UCLASS(MinimalAPI)
class UPFEntityGetGroup : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityGetGroupResponseDelegate OnSuccess;

    // Gets information about a group and its roles
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityGetGroup* GetGroup(class APlayerController* PlayerController, const FBPEntityGetGroupRequest& InGetGroupRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityGetGroupRequest Request;
    PlayFab::UPlayFabEntityAPI::FGetGroupDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FGetGroupResponse& Result);
};
