// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityGetProfiles.generated.h"

UCLASS(MinimalAPI)
class UPFEntityGetProfiles : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityGetEntityProfilesResponseDelegate OnSuccess;

    // Retrieves the entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Account Management")
        static UPFEntityGetProfiles* GetProfiles(class APlayerController* PlayerController, const FBPEntityGetEntityProfilesRequest& InGetEntityProfilesRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityGetEntityProfilesRequest Request;
    PlayFab::UPlayFabEntityAPI::FGetProfilesDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FGetEntityProfilesResponse& Result);
};
