// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityGetFiles.generated.h"

UCLASS(MinimalAPI)
class UPFEntityGetFiles : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityGetFilesResponseDelegate OnSuccess;

    // Retrieves file metadata from an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|File")
        static UPFEntityGetFiles* GetFiles(class APlayerController* PlayerController, const FBPEntityGetFilesRequest& InGetFilesRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityGetFilesRequest Request;
    PlayFab::UPlayFabEntityAPI::FGetFilesDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FGetFilesResponse& Result);
};
