// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityListMembership.generated.h"

UCLASS(MinimalAPI)
class UPFEntityListMembership : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityListMembershipResponseDelegate OnSuccess;

    // Lists all groups and roles for an entity
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityListMembership* ListMembership(class APlayerController* PlayerController, const FBPEntityListMembershipRequest& InListMembershipRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityListMembershipRequest Request;
    PlayFab::UPlayFabEntityAPI::FListMembershipDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FListMembershipResponse& Result);
};
