// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityUnblockEntity.generated.h"

UCLASS(MinimalAPI)
class UPFEntityUnblockEntity : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Unblocks a list of entities from joining a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityUnblockEntity* UnblockEntity(class APlayerController* PlayerController, const FBPEntityUnblockEntityRequest& InUnblockEntityRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityUnblockEntityRequest Request;
    PlayFab::UPlayFabEntityAPI::FUnblockEntityDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result);
};
