// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntitySetProfilePolicy.generated.h"

UCLASS(MinimalAPI)
class UPFEntitySetProfilePolicy : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntitySetEntityProfilePolicyResponseDelegate OnSuccess;

    // Sets the profiles access policy
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Account Management")
        static UPFEntitySetProfilePolicy* SetProfilePolicy(class APlayerController* PlayerController, const FBPEntitySetEntityProfilePolicyRequest& InSetEntityProfilePolicyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntitySetEntityProfilePolicyRequest Request;
    PlayFab::UPlayFabEntityAPI::FSetProfilePolicyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FSetEntityProfilePolicyResponse& Result);
};
