// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityIsMember.generated.h"

UCLASS(MinimalAPI)
class UPFEntityIsMember : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityIsMemberResponseDelegate OnSuccess;

    // Checks to see if an entity is a member of a group or role within the group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityIsMember* IsMember(class APlayerController* PlayerController, const FBPEntityIsMemberRequest& InIsMemberRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityIsMemberRequest Request;
    PlayFab::UPlayFabEntityAPI::FIsMemberDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FIsMemberResponse& Result);
};
