// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityGetObjects.generated.h"

UCLASS(MinimalAPI)
class UPFEntityGetObjects : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityGetObjectsResponseDelegate OnSuccess;

    // Retrieves objects from an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Object")
        static UPFEntityGetObjects* GetObjects(class APlayerController* PlayerController, const FBPEntityGetObjectsRequest& InGetObjectsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityGetObjectsRequest Request;
    PlayFab::UPlayFabEntityAPI::FGetObjectsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FGetObjectsResponse& Result);
};
