// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityListGroupMembers.generated.h"

UCLASS(MinimalAPI)
class UPFEntityListGroupMembers : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityListGroupMembersResponseDelegate OnSuccess;

    // Lists all members for a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityListGroupMembers* ListGroupMembers(class APlayerController* PlayerController, const FBPEntityListGroupMembersRequest& InListGroupMembersRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityListGroupMembersRequest Request;
    PlayFab::UPlayFabEntityAPI::FListGroupMembersDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FListGroupMembersResponse& Result);
};
