// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityCreateRole.generated.h"

UCLASS(MinimalAPI)
class UPFEntityCreateRole : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityCreateGroupRoleResponseDelegate OnSuccess;

    // Creates a new group role.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityCreateRole* CreateRole(class APlayerController* PlayerController, const FBPEntityCreateGroupRoleRequest& InCreateGroupRoleRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityCreateGroupRoleRequest Request;
    PlayFab::UPlayFabEntityAPI::FCreateRoleDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FCreateGroupRoleResponse& Result);
};
