// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityListMembershipOpportunities.generated.h"

UCLASS(MinimalAPI)
class UPFEntityListMembershipOpportunities : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityListMembershipOpportunitiesResponseDelegate OnSuccess;

    // Lists all outstanding invitations and group applications for an entity
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityListMembershipOpportunities* ListMembershipOpportunities(class APlayerController* PlayerController, const FBPEntityListMembershipOpportunitiesRequest& InListMembershipOpportunitiesRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityListMembershipOpportunitiesRequest Request;
    PlayFab::UPlayFabEntityAPI::FListMembershipOpportunitiesDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FListMembershipOpportunitiesResponse& Result);
};
