// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityCreateGroup.generated.h"

UCLASS(MinimalAPI)
class UPFEntityCreateGroup : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityCreateGroupResponseDelegate OnSuccess;

    // Creates a new group.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityCreateGroup* CreateGroup(class APlayerController* PlayerController, const FBPEntityCreateGroupRequest& InCreateGroupRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityCreateGroupRequest Request;
    PlayFab::UPlayFabEntityAPI::FCreateGroupDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FCreateGroupResponse& Result);
};
