// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityRemoveGroupInvitation.generated.h"

UCLASS(MinimalAPI)
class UPFEntityRemoveGroupInvitation : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Removes an invitation join a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityRemoveGroupInvitation* RemoveGroupInvitation(class APlayerController* PlayerController, const FBPEntityRemoveGroupInvitationRequest& InRemoveGroupInvitationRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityRemoveGroupInvitationRequest Request;
    PlayFab::UPlayFabEntityAPI::FRemoveGroupInvitationDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result);
};
