// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntitySetGlobalPolicy.generated.h"

UCLASS(MinimalAPI)
class UPFEntitySetGlobalPolicy : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Sets the global title access policy 
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Account Management")
        static UPFEntitySetGlobalPolicy* SetGlobalPolicy(class APlayerController* PlayerController, const FBPEntitySetGlobalPolicyRequest& InSetGlobalPolicyRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntitySetGlobalPolicyRequest Request;
    PlayFab::UPlayFabEntityAPI::FSetGlobalPolicyDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FSetGlobalPolicyResponse& Result);
};
