// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityApplyToGroup.generated.h"

UCLASS(MinimalAPI)
class UPFEntityApplyToGroup : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityApplyToGroupResponseDelegate OnSuccess;

    // Applies to join a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityApplyToGroup* ApplyToGroup(class APlayerController* PlayerController, const FBPEntityApplyToGroupRequest& InApplyToGroupRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityApplyToGroupRequest Request;
    PlayFab::UPlayFabEntityAPI::FApplyToGroupDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FApplyToGroupResponse& Result);
};
