// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityListGroupBlocks.generated.h"

UCLASS(MinimalAPI)
class UPFEntityListGroupBlocks : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityListGroupBlocksResponseDelegate OnSuccess;

    // Lists all entities blocked from joining a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityListGroupBlocks* ListGroupBlocks(class APlayerController* PlayerController, const FBPEntityListGroupBlocksRequest& InListGroupBlocksRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityListGroupBlocksRequest Request;
    PlayFab::UPlayFabEntityAPI::FListGroupBlocksDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FListGroupBlocksResponse& Result);
};
