// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntitySetObjects.generated.h"

UCLASS(MinimalAPI)
class UPFEntitySetObjects : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntitySetObjectsResponseDelegate OnSuccess;

    // Sets objects on an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Object")
        static UPFEntitySetObjects* SetObjects(class APlayerController* PlayerController, const FBPEntitySetObjectsRequest& InSetObjectsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntitySetObjectsRequest Request;
    PlayFab::UPlayFabEntityAPI::FSetObjectsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FSetObjectsResponse& Result);
};
