// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityInitiateFileUploads.generated.h"

UCLASS(MinimalAPI)
class UPFEntityInitiateFileUploads : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityInitiateFileUploadsResponseDelegate OnSuccess;

    // Initiates file uploads to an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|File")
        static UPFEntityInitiateFileUploads* InitiateFileUploads(class APlayerController* PlayerController, const FBPEntityInitiateFileUploadsRequest& InInitiateFileUploadsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityInitiateFileUploadsRequest Request;
    PlayFab::UPlayFabEntityAPI::FInitiateFileUploadsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FInitiateFileUploadsResponse& Result);
};
