// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityAcceptGroupApplication.generated.h"

UCLASS(MinimalAPI)
class UPFEntityAcceptGroupApplication : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FEmptyPlayFabDelegate OnSuccess; 

    // Accepts an outstanding invitation to to join a group
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityAcceptGroupApplication* AcceptGroupApplication(class APlayerController* PlayerController, const FBPEntityAcceptGroupApplicationRequest& InAcceptGroupApplicationRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityAcceptGroupApplicationRequest Request;
    PlayFab::UPlayFabEntityAPI::FAcceptGroupApplicationDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FEmptyResult& Result);
};
