// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityUpdateRole.generated.h"

UCLASS(MinimalAPI)
class UPFEntityUpdateRole : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityUpdateGroupRoleResponseDelegate OnSuccess;

    // Updates metadata about a role.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Groups")
        static UPFEntityUpdateRole* UpdateRole(class APlayerController* PlayerController, const FBPEntityUpdateGroupRoleRequest& InUpdateGroupRoleRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityUpdateGroupRoleRequest Request;
    PlayFab::UPlayFabEntityAPI::FUpdateRoleDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FUpdateGroupRoleResponse& Result);
};
