// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityDeleteFiles.generated.h"

UCLASS(MinimalAPI)
class UPFEntityDeleteFiles : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityDeleteFilesResponseDelegate OnSuccess;

    // Delete files on an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|File")
        static UPFEntityDeleteFiles* DeleteFiles(class APlayerController* PlayerController, const FBPEntityDeleteFilesRequest& InDeleteFilesRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityDeleteFilesRequest Request;
    PlayFab::UPlayFabEntityAPI::FDeleteFilesDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FDeleteFilesResponse& Result);
};
