// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityGetProfile.generated.h"

UCLASS(MinimalAPI)
class UPFEntityGetProfile : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityGetEntityProfileResponseDelegate OnSuccess;

    // Retrieves the entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|Account Management")
        static UPFEntityGetProfile* GetProfile(class APlayerController* PlayerController, const FBPEntityGetEntityProfileRequest& InGetEntityProfileRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityGetEntityProfileRequest Request;
    PlayFab::UPlayFabEntityAPI::FGetProfileDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FGetEntityProfileResponse& Result);
};
