// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabEntityAPI.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Proxy/PlayFabEntityBPDataModels.h"
#include "PFEntityAbortFileUploads.generated.h"

UCLASS(MinimalAPI)
class UPFEntityAbortFileUploads : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPEntityAbortFileUploadsResponseDelegate OnSuccess;

    // Abort pending file uploads to an entity's profile.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Entity|File")
        static UPFEntityAbortFileUploads* AbortFileUploads(class APlayerController* PlayerController, const FBPEntityAbortFileUploadsRequest& InAbortFileUploadsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPEntityAbortFileUploadsRequest Request;
    PlayFab::UPlayFabEntityAPI::FAbortFileUploadsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::EntityModels::FAbortFileUploadsResponse& Result);
};
