// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminRevokeInventoryItems.generated.h"

UCLASS(MinimalAPI)
class UPFAdminRevokeInventoryItems : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminRevokeInventoryItemsResultDelegate OnSuccess;

    // Revokes access for up to 25 items across multiple users and characters.
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Player Item Management")
        static UPFAdminRevokeInventoryItems* RevokeInventoryItems(class APlayerController* PlayerController, const FBPAdminRevokeInventoryItemsRequest& InRevokeInventoryItemsRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminRevokeInventoryItemsRequest Request;
    PlayFab::UPlayFabAdminAPI::FRevokeInventoryItemsDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FRevokeInventoryItemsResult& Result);
};
