// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFServerRevokeInventoryItems.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFServerRevokeInventoryItems::UPFServerRevokeInventoryItems(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabServerAPI::FRevokeInventoryItemsDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFServerRevokeInventoryItems* UPFServerRevokeInventoryItems::RevokeInventoryItems(class APlayerController* PlayerController, const FBPServerRevokeInventoryItemsRequest& InRevokeInventoryItemsRequest)
{
    UPFServerRevokeInventoryItems* Proxy = NewObject<UPFServerRevokeInventoryItems>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InRevokeInventoryItemsRequest;
    
    return Proxy;
}

void UPFServerRevokeInventoryItems::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabServerPtr ServerAPI = IPlayFabModuleInterface::Get().GetServerAPI();

    bool CallResult = false;

    if (ServerAPI.IsValid())
    {
        CallResult = ServerAPI->RevokeInventoryItems(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFServerRevokeInventoryItems::OnSuccessCallback(const PlayFab::ServerModels::FRevokeInventoryItemsResult& Result)
{
    FBPServerRevokeInventoryItemsResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
